# Basic site info
name: Vincent's Blog
description: Cybersecurity & Tech Insights
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Important config settings
baseurl: ""  # Blank for user/organization GitHub Pages
url: "https://joyboyreturns.github.io"
permalink: /:year/:month/:day/:title.html

# Footer & social links (customize if you want)
footer-links:
  github: joyboyreturns/vincent.github.io

# Markdown & plugins (if present)
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude these files from site build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
