# Site Settings
name: "Code Beacon"
description: "Cybersecurity & Tech Insights"
avatar: "https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png"

# URL & Baseurl
url: "https://codebeacon.info"
baseurl: ""

# Permalinks
permalink: /:year/:month/:day/:title.html

# Posts pagination
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
paginate: 10
paginate_path: "/page:num/"

# Markdown & Syntax Highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Timezone (so your dates render in IST)
timezone: "Asia/Kolkata"

# Files to exclude from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

  # Files Jekyll will preserve in the _site folder even if excluded
keep_files:
  - CNAME

# Footer & Social Links
footer-links:
  github: "joyboyreturns/vincent.github.io"
