# Site Settings
name: "Vincent's Blog"
description: "Cybersecurity & Tech Insights"
avatar: "https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png"

# URL & Baseurl
url: "https://codebeacon.info"     # Use your custom domain here!
baseurl: ""                        # Leave empty for a user/org page

# Permalink format for posts
permalink: /:year/:month/:day/:title.html

# Footer & Social Links
footer-links:
  github: "joyboyreturns/vincent.github.io"

# Markdown & Syntax Highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
 

# Files to exclude from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
