# Site Settings
name: "Vincent's Blog"
description: "Cybersecurity & Tech Insights"
avatar: "https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png"

# URL & Baseurl
url: "https://codebeacon.info"
baseurl: ""

# Permalink format for posts
permalink: /:year/:month/:day/:title.html

# Pagination (show 10 posts per page)
paginate: 10
paginate_path: "/page:num/"

# Footer & Social Links
footer-links:
  github: "joyboyreturns/vincent.github.io"

# Markdown & Syntax Highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Files to exclude from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
